// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/wxlbd/polaris/internal/application/service"
	"github.com/wxlbd/polaris/internal/infrastructure/config"
	"github.com/wxlbd/polaris/internal/infrastructure/logger"
	"github.com/wxlbd/polaris/internal/infrastructure/persistence"
	"github.com/wxlbd/polaris/internal/infrastructure/wechat"
	"github.com/wxlbd/polaris/internal/interface/http/handler"
	"github.com/wxlbd/polaris/internal/interface/http/router"
)

// Injectors from wire.go:

// InitApp 初始化应用(Wire自动生成)
func InitApp(cfg *config.Config) (*App, error) {
	db, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewUserRepository(db)
	client, err := persistence.NewRedis(cfg)
	if err != nil {
		return nil, err
	}
	wechatClient := wechat.NewClient(cfg, client)
	authService := service.NewAuthService(userRepository, cfg, wechatClient)
	appVersionRepository := persistence.NewAppVersionRepository(db)
	appVersionService := service.NewAppVersionService(appVersionRepository)
	authHandler := handler.NewAuthHandler(authService, appVersionService)
	uploadService := service.NewUploadService(cfg)
	uploadHandler := handler.NewUploadHandler(uploadService)
	zapLogger, err := logger.NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	engine := router.NewRouter(cfg, authHandler, uploadHandler, zapLogger)
	app := NewApp(cfg, engine)
	return app, nil
}
